prowjob_namespace: prow
pod_namespace: prow
periodics:

tide:
  queries:
  - repos:
    - servicemesher/website
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-rebase

  merge_method:
    servicemesher/website: squash

  target_url: https://prow.servicemesher.com/tide

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true

