client_id: 43c958168f1c2f2xxxxx
client_secret: 7b38b9ab9bda37ac85cf2a057ec196da87exxxxx
redirect_url: https://prow.servicemesher.com/github-login/redirect
final_redirect_url: https://prow.servicemesher.com/pr
